### PR TITLE
Fix #85

### LINKED ISSUE #85: Setting the `host` header on the request is not reflected on the proxied request.
### Version

`4.5.8`

### Context

When using the `http-proxy` and setting the `Host` header, it depends on whether to set the header as `Host` or `host`. With `Host`, the value is correctly reflected on the server, the proxy is sending the request to. But if it is `host`, the header value is not present on the request at the server.

By RFC 9110, header (or field) names are case-insensitive:

> Field names are case-insensitive

(Source: https://www.rfc-editor.org/rfc/rfc9110.html#fields)

### Do you have a reproducer?

A reproducer is attached as a zip. It is generated with the `vertx-starter` uses `vertx-web` and `vertx-http-proxy`.

[reproducer.zip](https://github.com/user-attachments/files/15954364/reproducer.zip)

### Steps to reproduce

1. `mvn test`
2. observe 1 out of 2 test failures.

### PR DESCRIPTION
**Pull request by fbuetler**
Fixes https://github.com/eclipse-vertx/vertx-http-proxy/issues/85

`null` is used as a signal, so we should not set a default in the constructor. 

https://github.com/fbuetler/vertx-http-proxy/blob/a97630bc9ee465f073fbefd5febbe12cdc43d78b/src/main/java/io/vertx/httpproxy/impl/ProxiedRequest.java#L173

With this, the updated reproducer provided in the issue passes.

### CODE REVIEW

File: src/main/java/io/vertx/httpproxy/impl/ProxiedRequest.java [hunk 1]
```diff
@@ -72,7 +72,6 @@ public ProxiedRequest(HttpServerRequest proxiedRequest) {
     this.absoluteURI = proxiedRequest.absoluteURI();
     this.proxiedRequest = proxiedRequest;
     this.context = (ContextInternal) ((HttpServerRequestInternal) proxiedRequest).context();
-    this.authority = proxiedRequest.authority();
```
Comment (vietj) [inline src/main/java/io/vertx/httpproxy/impl/ProxiedRequest.java:75]: I'd prefer this.authority = null with a comment

**Comment by fbuetler** [comment]
There was a test that should have caught this issue but was implemented incorrectly. 

The test was setting the `host` header on the request that is created in the proxy, but in the proxy implementation [the host is ignored](https://github.com/eclipse-vertx/vertx-http-proxy/blob/78a73651a5ddd71674a1ae0ae12c0b4d50d22ad9/src/main/java/io/vertx/httpproxy/impl/ProxiedRequest.java#L172), unfortunately.

I fixed the test and could verify that without the fix included in this PR, the test would fail but if included, it succeeds.

I also fixed some whitespace issues, if you don't mind including them here.

**Review by tsegismont — APPROVED** [review]
LGTM, thank you @fbuetler

**Comment by tsegismont** [comment]
Can you please look at the test failures? Thanks

**Comment by fbuetler** [comment]
Ready for another round. They pass now on my machine.

**Review by tsegismont — APPROVED** [review]
Thanks for the udates @fbuetler !
