### PR TITLE
Apply interceptors for WebSocket handshake

### LINKED ISSUE #48: Interceptors are not applied for websocket upgrades
### Version

4.3.8

### Context

I investigated an issue, where websocket upgrades were failing. We have a service handling websockets living behind the `vertx-http-proxy`. This service is living on a different root path, than the `vertx-http-proxy` is exposing. Hence a path prefix is removed in the `vertx-http-proxy` with the help of a `ProxyInterceptor`. This works for normal http requests.

However, it turns out the `ProxyInterceptor`s are not applied for websocket upgrades as websocket upgrades are [handled and returned](https://github.com/eclipse-vertx/vertx-http-proxy/blob/4.3.8/src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java#L85) before the [interceptors are applied](https://github.com/eclipse-vertx/vertx-http-proxy/blob/4.3.8/src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java#L95).

This behaviour results in the path prefix not being removed and the service running behind the proxy returning a 404 for the websocket upgrade.

### PR DESCRIPTION
**Pull request by wzy1935**
Should close #48.

Now interceptor can be applied to WebSocket handshake packets. Since most interceptors should not modify packets during the WebSocket establishment, they are not applied by default. They can be used by overwriting `allowApplyToWebSocket()` method or wrapping with `WebSocketInterceptor.allow()` method.

### CODE REVIEW

**Comment by vietj** [comment]
can you add a test to ensure the correctness ?

**Comment by wzy1935** [comment]
Tests added, thanks!

File: src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java [hunk 1]
```diff
@@ -180,8 +133,25 @@ public ProxyRequest request() {
     public Future<ProxyResponse> sendRequest() {
       if (filters.hasNext()) {
         ProxyInterceptor next = filters.next();
+        if (isWebSocket && !next.allowApplyToWebSocket()) {
```
Comment (tsegismont) [inline src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java:136]: If the next interceptor doesn't support  websockets, shouldn't we only skip it instead of stopping traversal?

Also, what happens if caching is enabled, and the cache interceptor is the first one in line? Can you add a test for this case?

**Review by tsegismont — COMMENTED** [review]
Good job @wzy1935 . Here are a few comments

File: src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java (hunk 1 above)
Comment (wzy1935) [reply src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java:136]: Current implementation is "skip it", since the traversal is implemented by recursion.

If caching is enabled, websocket packets will not be cached or operated since CacheFilter will be skipped. I added a test to prove it's functional but I think it's rather hard to test, so not sure if it's good enough.

File: src/main/asciidoc/index.adoc [hunk 2]
```diff
@@ -174,3 +176,12 @@ You can use body interceptor to create body transformations for common data type
 
 Please check the {@link io.vertx.httpproxy.interceptors.BodyTransformer} for other supported transformations.
 
+==== WebSocket interceptor
+
+You can use WebSocket interceptor to wrap a interceptor to let it allow WebSocket handling:
```
Comment (tsegismont) [inline src/main/asciidoc/index.adoc:181]:
```suggestion
You can use WebSocket interceptor to wrap an interceptor to let it allow WebSocket handling:
```

**Review by tsegismont — APPROVED** [review]
This looks good to me. Perhaps can you add a few comments to the tests because the expectations and behavior did not seem immediately apparent, at least to me :smile:

**Review by tsegismont — APPROVED** [review]
LGTM, thank you @wzy1935
